/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.circuitwizardry.missioncontrol.features.pyro;

import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author marce
 */
public class MainChute extends PyroFeature {
    
    boolean atApogee = false;

    /**
     * Creates new form MainChute
     * @param parent
     */
    public MainChute(JPanel parent) {
        this.setSize(400, 90);
        this.setLocation(250, 5);
        initComponents();
        parent.add(this);
        super.setVisible(true);
    }
    
    @Override
    public String generateJson() {
        String output = "'apogee': '" + atApogee + "', ";
        output = output + "'height': " + height.getValue() + " }";
        return output;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        height = new javax.swing.JSlider();
        parachuteInfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        apogeeCheck = new javax.swing.JCheckBox();

        jLabel1.setText("Main Chute Deployment");

        height.setMajorTickSpacing(1500);
        height.setMaximum(1500);
        height.setMinorTickSpacing(50);
        height.setPaintTicks(true);
        height.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightStateChanged(evt);
            }
        });

        parachuteInfo.setText("<no selection>");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Or...");

        apogeeCheck.setText("Deploy at apogee");
        apogeeCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apogeeCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(parachuteInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(apogeeCheck))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apogeeCheck)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parachuteInfo)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void heightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_heightStateChanged
        // TODO add your handling code here:
        if (!atApogee) {
            parachuteInfo.setText("Main chute will be deployed at " + height.getValue() + " feet.");   
        }
    }//GEN-LAST:event_heightStateChanged

    private void apogeeCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apogeeCheckActionPerformed
        // TODO add your handling code here:
        atApogee = apogeeCheck.isSelected();
        if (atApogee) {
            parachuteInfo.setText("Main chute will be deployed AT APOGEE");
        } else {
            parachuteInfo.setText("Main chute will be deployed at " + height.getValue() + " feet.");   
        }
    }//GEN-LAST:event_apogeeCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox apogeeCheck;
    private javax.swing.JSlider height;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel parachuteInfo;
    // End of variables declaration//GEN-END:variables
}
